# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  MODULE: module1 

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout
       uses: actions/checkout@v3
       with:
          sparse-checkout: |
            ${{env.MODULE}}
          token: ${{ github.token }}

     - name: listof files
       run: |
         ls -la
         echo "$MODULE"
     - uses: dorny/paths-filter@v3
       id: filter
       with:
            # Enable listing of files matching each filter.
            # Paths to files will be available in `${FILTER_NAME}_files` output variable.
            # Paths will be formatted as JSON array
            token: ${{ github.token }}
            list-files: json
            

    # In this example all changed files are passed to the following action to do
    # some custom processing.
            filters: |
              changed:
                - '**'
     - name: print files
       run: |
        echo "${{ steps.filter.outputs.changed_files }}" 
        echo "${{ steps.filter.outputs.changed_files }}" | cut -d '/' -f 1
      
  
